apiVersion: v2
name: capacitor
description: A Helm chart for deploying capacitor, a general purpose UI for FluxCD
type: application
version: 0.3.0
# renovate: github=gimlet-io/capacitor
appVersion: 0.12.1
